name: Ensure SOMETHING File Consistency

on:
  pull_request:
    branches:
      - master

jobs:
  enforce-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # Fetch all history for all branches

      - name: Fetch target branch ${{ github.base_ref }}
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Check if SOMETHING file has changed
        id: check_something
        run: |
          # Check if the SOMETHING file is different between the PR and master
          if git diff --quiet origin/master...HEAD -- .github/SOMETHING; then
            echo "file_changed=false" >> "$GITHUB_ENV"
          else
            echo "file_changed=true" >> "$GITHUB_ENV"

      - name: Replace SOMETHING file if it has changed
        if: env.file_changed == 'true'
        run: |
          # Checkout the SOMETHING file from master
          git checkout origin/master -- .github/SOMETHING
          # Commit the change
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/SOMETHING
          git commit -m "Replace SOMETHING file with version from master"
          # Push the change back to the PR branch
          git push origin HEAD:${{ github.head_ref }}
